import { collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, setDoc, where, type Unsubscribe } from 'firebase/firestore';
import { firebaseAuth, firestoreDb } from '../lib/firebase';
import { appendExpertAuditLog, resolveActiveExpertWorkspaceId } from './expertsWorkspaceCore';
export type FormationPlanDay={id:string;formationId:string;cohortId:string;dayNumber:number;title:string;teachingItems:string[];date:string;mentorNotes:string;faq:string;status:'pending'|'done';createdAt:string;updatedAt?:string;};
async function workspaceId(){const u=firebaseAuth.currentUser;if(!u)throw new Error('AUTH_REQUIRED');const id=await resolveActiveExpertWorkspaceId(u);if(!id)throw new Error('WORKSPACE_REQUIRED');return id;}
function mapDay(id:string,data:Record<string,unknown>):FormationPlanDay{const t=(data.task&&typeof data.task==='object'?data.task:{}) as Record<string,unknown>;return{id,formationId:typeof t.formationId==='string'?t.formationId:'',cohortId:typeof t.cohortId==='string'?t.cohortId:'',dayNumber:typeof t.dayNumber==='number'?t.dayNumber:0,title:typeof t.planTitle==='string'?t.planTitle:(typeof t.title==='string'?t.title:''),teachingItems:Array.isArray(t.teachingItems)?t.teachingItems.filter((x):x is string=>typeof x==='string'):[],date:typeof t.dueDate==='string'?t.dueDate:'',mentorNotes:typeof t.mentorNotes==='string'?t.mentorNotes:'',faq:typeof t.faq==='string'?t.faq:'',status:t.status==='done'?'done':'pending',createdAt:typeof t.createdAt==='string'?t.createdAt:'',updatedAt:typeof t.updatedAt==='string'?t.updatedAt:undefined};}
export async function subscribeFormationPlan(cohortId:string,callback:(items:FormationPlanDay[])=>void):Promise<Unsubscribe>{const w=await workspaceId();const q=query(collection(firestoreDb,'expert_workspaces',w,'work_tasks'),where('task.workstream','==','formation-plan'));return onSnapshot(q,s=>callback(s.docs.map(d=>mapDay(d.id,d.data() as Record<string,unknown>)).filter(x=>x.cohortId===cohortId).sort((a,b)=>a.dayNumber-b.dayNumber||a.date.localeCompare(b.date))),()=>callback([]));}
export async function saveFormationPlanDay(input:{id?:string;formationId:string;cohortId:string;cohortTitle:string;dayNumber:number;title:string;teachingItems:string[];date?:string;mentorNotes?:string;faq?:string;status?:'pending'|'done'}):Promise<string>{const u=firebaseAuth.currentUser;if(!u)throw new Error('AUTH_REQUIRED');const w=await workspaceId();const id=input.id||`formation-plan-${input.cohortId}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;const now=new Date().toISOString();await setDoc(doc(firestoreDb,'expert_workspaces',w,'work_tasks',id),{schemaVersion:1,task:{id,clientId:'',clientName:input.cohortTitle,personId:'',title:`Día ${Math.max(1,Math.round(input.dayNumber))} · ${input.title.trim()||'Plan de formación'}`,type:'task',note:input.teachingItems.join('\n'),dueDate:input.date||'',dueTime:'',assignee:'Formación',assignedToUid:u.uid,assignedToName:u.displayName||u.email||'Mentor',createdByUid:u.uid,status:input.status||'pending',createdAt:now,source:'formation',sourceId:input.cohortId,sourceActionKind:'formation-plan',workstream:'formation-plan',formationId:input.formationId,cohortId:input.cohortId,dayNumber:Math.max(1,Math.round(input.dayNumber)),planTitle:input.title.trim(),teachingItems:input.teachingItems.map(x=>x.trim()).filter(Boolean),mentorNotes:(input.mentorNotes||'').trim(),faq:(input.faq||'').trim(),updatedAt:now,confirmationEmail:'not-required'},updatedAt:serverTimestamp()},{merge:true});return id;}
export async function deleteFormationPlanDay(id:string){const w=await workspaceId();await deleteDoc(doc(firestoreDb,'expert_workspaces',w,'work_tasks',id));}
export async function deleteEnrollmentRecord(enrollmentId:string){const w=await workspaceId();await deleteDoc(doc(firestoreDb,'expert_workspaces',w,'enrollments',enrollmentId));await appendExpertAuditLog({entityType:'enrollment',entityId:enrollmentId,action:'formation.enrollment_deleted',changes:{}}).catch(()=>{});}
