import React, { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle,
  CalendarDays,
  ChevronDown,
  ChevronRight,
  CircleGauge,
  Target
} from 'lucide-react';
import type { Language } from '../../i18n/LanguageContext';
import { getWorkPriority, loadTasks, WORKSPACE_STATE_EVENT, type WorkActionType, type WorkTask } from './workspaceState';

type RangeKey = 'week' | 'month' | 'year';
type MetricId = 'priority' | 'sessions' | 'clients' | 'leads';
type LocalText = { es: string; en: string };
type TrendPoint = { label: string; fullLabel: string; value: number };
type ClientRecord = { id: string; name: string; currentPhase?: string; nextSession?: string; nextAction?: string };
type Metric = { id: MetricId; label: LocalText; value: string; detail: LocalText; trend: LocalText; ringValue: number; ringTotal: number; colors: [string, string] };

const CLIENT_RECORD_STORAGE_KEY = 'gkais-experts-client-records-v2';
const BASE_METRICS: Metric[] = [
  { id: 'priority', label: { es: 'Trabajo prioritario', en: 'Priority Work' }, value: '0', detail: { es: 'acciones abiertas', en: 'open actions' }, trend: { es: 'cola operativa', en: 'operating queue' }, ringValue: 0, ringTotal: 1, colors: ['#A23A32', '#D67A32'] },
  { id: 'sessions', label: { es: 'Sesiones de hoy', en: 'Sessions Today' }, value: '3', detail: { es: '2 clientes · 1 lead', en: '2 clients · 1 lead' }, trend: { es: 'agenda del día', en: 'today agenda' }, ringValue: 2, ringTotal: 3, colors: ['#4556A6', '#74A9CF'] },
  { id: 'clients', label: { es: 'Clientes activos', en: 'Active Clients' }, value: '46', detail: { es: '+4 este mes', en: '+4 this month' }, trend: { es: '+9% vs mes anterior', en: '+9% vs previous month' }, ringValue: 43, ringTotal: 46, colors: ['#0A3F4D', '#78A892'] },
  { id: 'leads', label: { es: 'Nuevos leads', en: 'New Leads' }, value: '18', detail: { es: 'este mes', en: 'this month' }, trend: { es: '+12% vs mes anterior', en: '+12% vs previous month' }, ringValue: 14, ringTotal: 18, colors: ['#5C4D8A', '#7A9FC8'] }
];

const HISTORY: Record<'clients' | 'leads', Record<RangeKey, TrendPoint[]>> = {
  clients: {
    week: [{ label: 'Lun', fullLabel: 'Lun 21 sep', value: 0 }, { label: 'Mar', fullLabel: 'Mar 22 sep', value: 1 }, { label: 'Mié', fullLabel: 'Mié 23 sep', value: 0 }, { label: 'Jue', fullLabel: 'Jue 24 sep', value: 2 }, { label: 'Vie', fullLabel: 'Vie 25 sep', value: 0 }, { label: 'Sáb', fullLabel: 'Sáb 26 sep', value: 0 }, { label: 'Dom', fullLabel: 'Dom 27 sep', value: 1 }],
    month: [{ label: '01', fullLabel: '1 sep', value: 0 }, { label: '04', fullLabel: '4 sep', value: 1 }, { label: '07', fullLabel: '7 sep', value: 0 }, { label: '10', fullLabel: '10 sep', value: 1 }, { label: '13', fullLabel: '13 sep', value: 0 }, { label: '16', fullLabel: '16 sep', value: 1 }, { label: '19', fullLabel: '19 sep', value: 0 }, { label: '22', fullLabel: '22 sep', value: 2 }, { label: '25', fullLabel: '25 sep', value: 0 }, { label: '28', fullLabel: '28 sep', value: 1 }],
    year: [{ label: 'Oct', fullLabel: 'Oct 2025', value: 3 }, { label: 'Nov', fullLabel: 'Nov 2025', value: 4 }, { label: 'Dic', fullLabel: 'Dic 2025', value: 2 }, { label: 'Ene', fullLabel: 'Ene 2026', value: 5 }, { label: 'Feb', fullLabel: 'Feb 2026', value: 3 }, { label: 'Mar', fullLabel: 'Mar 2026', value: 6 }, { label: 'Abr', fullLabel: 'Abr 2026', value: 4 }, { label: 'May', fullLabel: 'May 2026', value: 5 }, { label: 'Jun', fullLabel: 'Jun 2026', value: 4 }, { label: 'Jul', fullLabel: 'Jul 2026', value: 6 }, { label: 'Ago', fullLabel: 'Ago 2026', value: 5 }, { label: 'Sep', fullLabel: 'Sep 2026', value: 4 }]
  },
  leads: {
    week: [{ label: 'Lun', fullLabel: 'Lun 21 sep', value: 2 }, { label: 'Mar', fullLabel: 'Mar 22 sep', value: 4 }, { label: 'Mié', fullLabel: 'Mié 23 sep', value: 1 }, { label: 'Jue', fullLabel: 'Jue 24 sep', value: 5 }, { label: 'Vie', fullLabel: 'Vie 25 sep', value: 3 }, { label: 'Sáb', fullLabel: 'Sáb 26 sep', value: 1 }, { label: 'Dom', fullLabel: 'Dom 27 sep', value: 2 }],
    month: [{ label: '01', fullLabel: '1 sep', value: 1 }, { label: '04', fullLabel: '4 sep', value: 3 }, { label: '07', fullLabel: '7 sep', value: 2 }, { label: '10', fullLabel: '10 sep', value: 4 }, { label: '13', fullLabel: '13 sep', value: 1 }, { label: '16', fullLabel: '16 sep', value: 5 }, { label: '19', fullLabel: '19 sep', value: 2 }, { label: '22', fullLabel: '22 sep', value: 4 }, { label: '25', fullLabel: '25 sep', value: 3 }, { label: '28', fullLabel: '28 sep', value: 2 }],
    year: [{ label: 'Oct', fullLabel: 'Oct 2025', value: 36 }, { label: 'Nov', fullLabel: 'Nov 2025', value: 41 }, { label: 'Dic', fullLabel: 'Dic 2025', value: 31 }, { label: 'Ene', fullLabel: 'Ene 2026', value: 45 }, { label: 'Feb', fullLabel: 'Feb 2026', value: 38 }, { label: 'Mar', fullLabel: 'Mar 2026', value: 52 }, { label: 'Abr', fullLabel: 'Abr 2026', value: 47 }, { label: 'May', fullLabel: 'May 2026', value: 55 }, { label: 'Jun', fullLabel: 'Jun 2026', value: 44 }, { label: 'Jul', fullLabel: 'Jul 2026', value: 59 }, { label: 'Ago', fullLabel: 'Ago 2026', value: 48 }, { label: 'Sep', fullLabel: 'Sep 2026', value: 18 }]
  }
};

function loadClientRecords(): ClientRecord[] {
  try { const parsed = JSON.parse(localStorage.getItem(CLIENT_RECORD_STORAGE_KEY) || '[]'); return Array.isArray(parsed) ? parsed : []; } catch { return []; }
}
function smoothPath(points: Array<{ x: number; y: number }>): string {
  if (!points.length) return '';
  let path = `M ${points[0].x} ${points[0].y}`;
  for (let index = 1; index < points.length; index += 1) { const previous = points[index - 1]; const current = points[index]; const control = (previous.x + current.x) / 2; path += ` C ${control} ${previous.y}, ${control} ${current.y}, ${current.x} ${current.y}`; }
  return path;
}
function priorityText(task: WorkTask, language: Language): { label: string; className: string } {
  const priority = getWorkPriority(task);
  if (priority === 'high') return { label: language === 'es' ? 'ALTA' : 'HIGH', className: 'bg-[#A23A32]/9 text-[#8D332C]' };
  if (priority === 'medium') return { label: language === 'es' ? 'MEDIA' : 'MEDIUM', className: 'bg-[#A46F16]/10 text-[#82570F]' };
  return { label: 'NORMAL', className: 'bg-[#0A3F4D]/8 text-[#0A3F4D]' };
}
function actionTypeText(type: WorkActionType, language: Language): string {
  if (type === 'email') return 'Email';
  if (type === 'whatsapp') return 'WhatsApp';
  if (type === 'call') return language === 'es' ? 'Llamada' : 'Call';
  if (type === 'meeting') return language === 'es' ? 'Reunión' : 'Meeting';
  return language === 'es' ? 'Tarea interna' : 'Internal task';
}

function HistoricalChart({ kind, range, setRange, language }: { kind: 'clients' | 'leads'; range: RangeKey; setRange: (range: RangeKey) => void; language: Language }) {
  const [hovered, setHovered] = useState<number | null>(null);
  const points = HISTORY[kind][range]; const width = 760; const height = 150; const padX = 46; const padRight = 24; const padY = 20;
  const rawMax = Math.max(1, ...points.map((point) => point.value)); const tickStep = Math.max(1, Math.ceil(rawMax / 4)); const yMax = tickStep * 4; const chartWidth = width - padX - padRight; const chartHeight = height - padY * 2;
  const plotted = points.map((point, index) => ({ x: padX + (index / Math.max(1, points.length - 1)) * chartWidth, y: height - padY - (point.value / yMax) * chartHeight }));
  const yTicks = [0, 1, 2, 3, 4].map((index) => yMax - tickStep * index); const total = points.reduce((sum, point) => sum + point.value, 0); const average = total / points.length; const peak = Math.max(...points.map((point) => point.value));
  const selected = hovered === null ? null : points[hovered]; const selectedPoint = hovered === null ? null : plotted[hovered]; const lineColor = kind === 'clients' ? '#0A6B66' : '#5357A6'; const linePath = smoothPath(plotted); const areaPath = plotted.length ? `${linePath} L ${plotted[plotted.length - 1].x} ${height - padY} L ${plotted[0].x} ${height - padY} Z` : '';
  const tooltipWidth = 128; const tooltipHeight = 42; const tooltipX = selectedPoint ? Math.min(width - padRight - tooltipWidth, Math.max(padX, selectedPoint.x - tooltipWidth / 2)) : 0; const tooltipY = selectedPoint ? (selectedPoint.y < 58 ? selectedPoint.y + 10 : selectedPoint.y - tooltipHeight - 10) : 0;
  return <section className="mt-4 rounded-2xl border border-black/8 bg-white p-4 shadow-[0_8px_24px_rgba(10,10,10,0.025)] md:p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{kind === 'clients' ? (language === 'es' ? 'Histórico de clientes' : 'Client history') : (language === 'es' ? 'Histórico de leads' : 'Lead history')}</p><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-black/42"><span>Total <strong className="text-black/65">{total}</strong></span><span>{language === 'es' ? 'Promedio' : 'Average'} <strong className="text-black/65">{average.toFixed(1)}</strong></span><span>{language === 'es' ? 'Pico' : 'Peak'} <strong className="text-black/65">{peak}</strong></span></div></div><div className="inline-flex rounded-full border border-black/8 bg-[#F7F7F5] p-1">{(['week', 'month', 'year'] as RangeKey[]).map((item) => <button key={item} type="button" onClick={() => setRange(item)} className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${range === item ? 'bg-[#111413] text-white' : 'text-black/40 hover:text-black'}`}>{item === 'week' ? (language === 'es' ? 'Semana' : 'Week') : item === 'month' ? (language === 'es' ? 'Mes' : 'Month') : (language === 'es' ? 'Año' : 'Year')}</button>)}</div></div>
    <div className="mt-3 h-[176px]"><svg viewBox={`0 0 ${width} ${height}`} className="h-[150px] w-full" role="img" onMouseLeave={() => setHovered(null)}><defs><linearGradient id={`history-fill-${kind}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={lineColor} stopOpacity="0.26" /><stop offset="65%" stopColor={lineColor} stopOpacity="0.08" /><stop offset="100%" stopColor={lineColor} stopOpacity="0" /></linearGradient></defs>{yTicks.map((value, index) => { const y = padY + (index / 4) * chartHeight; return <g key={`${kind}-${value}-${index}`}><line x1={padX} x2={width - padRight} y1={y} y2={y} stroke="currentColor" strokeOpacity="0.055" /><text x={padX - 10} y={y + 3} textAnchor="end" fill="currentColor" fillOpacity="0.34" fontSize="9">{value}</text></g>; })}<path d={areaPath} fill={`url(#history-fill-${kind})`} /><path d={linePath} fill="none" stroke={lineColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />{selectedPoint && <line x1={selectedPoint.x} x2={selectedPoint.x} y1={padY} y2={height - padY} stroke={lineColor} strokeOpacity="0.16" strokeDasharray="3 4" />}{plotted.map((point, index) => <g key={points[index].fullLabel} onMouseEnter={() => setHovered(index)} className="cursor-crosshair"><circle cx={point.x} cy={point.y} r="13" fill="transparent" /><circle cx={point.x} cy={point.y} r={hovered === index ? 4 : 2.75} fill="white" stroke={lineColor} strokeWidth={hovered === index ? 2 : 1.5} /></g>)}{selected && selectedPoint && <g pointerEvents="none"><rect x={tooltipX} y={tooltipY} width={tooltipWidth} height={tooltipHeight} rx="8" fill="#111413" /><text x={tooltipX + 10} y={tooltipY + 16} fill="white" fontSize="10" fontWeight="600">{selected.fullLabel}</text><text x={tooltipX + 10} y={tooltipY + 31} fill="rgba(255,255,255,.68)" fontSize="9">{selected.value} {kind === 'clients' ? (language === 'es' ? 'clientes' : 'clients') : 'leads'}</text></g>}</svg><div className="flex justify-between text-[9px] font-medium text-black/32" style={{ paddingLeft: `${padX}px`, paddingRight: `${padRight}px` }}>{points.map((point, index) => <span key={point.fullLabel} className={points.length > 8 && index % 2 !== 0 ? 'hidden sm:block' : ''}>{point.label}</span>)}</div></div>
  </section>;
}

function MetricRing({ metric }: { metric: Metric }) { const percentage = Math.max(0, Math.min(100, (metric.ringValue / Math.max(1, metric.ringTotal)) * 100)); return <div className="relative h-12 w-12 shrink-0 rounded-full" style={{ background: `conic-gradient(${metric.colors[0]} 0 ${percentage / 2}%, ${metric.colors[1]} ${percentage / 2}% ${percentage}%, #E7E7E3 ${percentage}% 100%)` }}><div className="absolute inset-[4px] grid place-items-center rounded-full bg-white text-[9px] font-semibold text-black/60">{metric.ringValue}/{metric.ringTotal}</div></div>; }

export function DashboardHistory({ language, onNavigate, onOpenClient, onStartSession }: { language: Language; onNavigate: (id: string) => void; onOpenClient: (id: string) => void; onStartSession: (id: string) => void }) {
  const [expanded, setExpanded] = useState<'clients' | 'leads' | null>(null); const [ranges, setRanges] = useState<Record<'clients' | 'leads', RangeKey>>({ clients: 'month', leads: 'month' }); const [tasks, setTasks] = useState<WorkTask[]>(loadTasks); const [clients, setClients] = useState<ClientRecord[]>(loadClientRecords);
  useEffect(() => { const refresh = () => { setTasks(loadTasks()); setClients(loadClientRecords()); }; window.addEventListener(WORKSPACE_STATE_EVENT, refresh); window.addEventListener('storage', refresh); return () => { window.removeEventListener(WORKSPACE_STATE_EVENT, refresh); window.removeEventListener('storage', refresh); }; }, []);
  const openTasks = useMemo(() => tasks.filter((task) => task.status !== 'done' && !task.deletedAt).sort((a, b) => `${a.dueDate || '9999-12-31'}${a.dueTime || '23:59'}`.localeCompare(`${b.dueDate || '9999-12-31'}${b.dueTime || '23:59'}`)), [tasks]);
  const metrics = useMemo(() => BASE_METRICS.map((metric) => metric.id === 'priority' ? { ...metric, value: String(openTasks.length), ringValue: Math.min(openTasks.length, 7), ringTotal: Math.max(1, openTasks.length) } : metric), [openTasks.length]);
  const signals = useMemo(() => { const result: Array<{ id: string; name: string; label: string; reason: string }> = []; clients.forEach((client) => { const phase = (client.currentPhase || '').toLowerCase(); const nextSession = (client.nextSession || '').trim(); if (phase.includes('cierre') || phase.includes('continuidad') || phase.includes('renov')) result.push({ id: client.id, name: client.name, label: language === 'es' ? 'Plan cerca de cierre' : 'Plan nearing close', reason: language === 'es' ? 'Conviene revisar resultados, continuidad y próxima etapa.' : 'Review results, continuity and the next stage.' }); else if (!nextSession || /coordinar|schedule|pendiente/i.test(nextSession)) result.push({ id: client.id, name: client.name, label: language === 'es' ? 'Sin próxima sesión' : 'No next session', reason: language === 'es' ? 'La relación no tiene una próxima reunión confirmada.' : 'The relationship has no confirmed next meeting.' }); }); return result.slice(0, 3); }, [clients, language]);
  const agenda = useMemo(() => clients.filter((client) => (client.nextSession || '').trim()).slice(0, 5), [clients]);
  void onStartSession;
  return <>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const expandable = metric.id === 'clients' || metric.id === 'leads'; const isExpanded = expanded === metric.id; return <article key={metric.id} className="rounded-2xl border border-black/10 bg-white p-5 shadow-[0_10px_30px_rgba(10,10,10,0.035)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-black/45">{metric.label[language]}</p><strong className="mt-3 block text-3xl font-semibold tracking-[-0.04em]">{metric.value}</strong><span className="mt-1 block text-xs text-black/45">{metric.detail[language]}</span></div><MetricRing metric={metric} /></div>{expandable ? <button type="button" onClick={() => setExpanded(isExpanded ? null : metric.id as 'clients' | 'leads')} className="mt-4 flex w-full items-center justify-between border-t border-black/5 pt-3 text-left text-xs text-black/55"><span>{metric.trend[language]}</span><ChevronDown className={`h-3.5 w-3.5 transition ${isExpanded ? 'rotate-180' : ''}`} /></button> : <div className="mt-4 border-t border-black/5 pt-3 text-xs text-black/55">{metric.trend[language]}</div>}</article>; })}</div>
    {expanded && <HistoricalChart kind={expanded} range={ranges[expanded]} setRange={(range) => setRanges((current) => ({ ...current, [expanded]: range }))} language={language} />}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_0.8fr]">
      <section className="rounded-2xl border border-black/10 bg-white p-5 shadow-[0_10px_30px_rgba(10,10,10,0.03)] md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#0A3F4D]">{language === 'es' ? 'EJECUCIÓN' : 'EXECUTION'}</p><h2 className="mt-2 text-xl font-semibold">{language === 'es' ? 'Por hacer hoy' : 'Due today'}</h2><p className="mt-1 text-sm text-black/50">{language === 'es' ? 'Prioridad, tipo de tarea y responsable.' : 'Priority, task type and assignee.'}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#0A3F4D]/8 px-3 py-2 text-xs font-semibold text-[#0A3F4D]">{openTasks.length}</span><button type="button" onClick={() => onNavigate('priority')} className="inline-flex items-center gap-2 rounded-full bg-[#111413] px-4 py-2.5 text-xs font-semibold text-white">{language === 'es' ? 'Trabajo prioritario' : 'Priority work'}<ChevronRight className="h-3.5 w-3.5" /></button></div></div><div className="mt-4 divide-y divide-black/5">{openTasks.length === 0 && <div className="py-5 text-sm text-black/45">{language === 'es' ? 'No hay tareas abiertas.' : 'No open tasks.'}</div>}{openTasks.slice(0, 5).map((task) => { const priority = priorityText(task, language); return <div key={task.id} className="grid gap-3 py-4 first:pt-1 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{task.title}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${priority.className}`}>{priority.label}</span><span className="rounded-full bg-black/[0.045] px-2 py-0.5 text-[9px] font-semibold text-black/50">{actionTypeText(task.type, language)}</span></div><p className="mt-1 text-xs text-black/45">{task.clientName} · {task.assignee}</p></div><div className="text-left md:text-right"><p className="text-xs font-semibold text-black/65">{task.dueTime || (language === 'es' ? 'Sin hora' : 'No time')}</p><p className="mt-1 text-[10px] text-black/35">{task.dueDate || (language === 'es' ? 'Sin fecha' : 'No date')}</p></div></div>; })}</div></section>
      <div className="grid content-start gap-6"><section className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-black/40">AGENDA</p><h2 className="mt-2 text-lg font-semibold">{language === 'es' ? 'Próximas sesiones' : 'Upcoming sessions'}</h2></div><CalendarDays className="h-5 w-5 text-[#0A3F4D]" /></div><div className="mt-4 space-y-2">{agenda.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-black/6 p-3"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.name}</span><span className="mt-1 block truncate text-[10px] text-black/42">{item.nextSession}</span></span><button type="button" onClick={() => onOpenClient(item.id)} className="inline-flex items-center gap-1.5 rounded-full border border-black/10 bg-white px-3 py-1.5 text-[10px] font-semibold text-black/60">{language === 'es' ? 'Ver ficha' : 'Open record'}<ChevronRight className="h-3 w-3" /></button></div>)}{agenda.length === 0 && <p className="text-sm text-black/45">{language === 'es' ? 'No hay próximas sesiones registradas.' : 'No upcoming sessions recorded.'}</p>}</div></section>
      <section className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#A46F16]">THE RADAR</p><h2 className="mt-2 text-lg font-semibold">{language === 'es' ? 'Señales de relación' : 'Relationship signals'}</h2></div><span className="rounded-full bg-[#A46F16]/10 px-2.5 py-1 text-[10px] font-semibold text-[#82570F]">{signals.length}</span></div><div className="mt-4 space-y-3">{signals.length === 0 && <p className="text-sm text-black/45">{language === 'es' ? 'No hay señales críticas activas.' : 'No critical signals are active.'}</p>}{signals.map((item) => <button key={`${item.id}-${item.label}`} type="button" onClick={() => onOpenClient(item.id)} className="w-full rounded-xl border border-black/6 p-3 text-left"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold">{item.name}</p><ChevronRight className="h-3.5 w-3.5 text-black/30" /></div><p className="mt-1 text-[10px] font-semibold text-[#82570F]">{item.label}</p><p className="mt-1 text-[10px] leading-4 text-black/45">{item.reason}</p></button>)}</div></section></div>
    </div>
    <section className="mt-6 grid gap-4 md:grid-cols-3">{[[language === 'es' ? 'Renovaciones <30 días' : 'Renewals <30 days','6',Target],[language === 'es' ? 'Sin próxima acción' : 'No next action',String(clients.filter((client) => !(client.nextAction || '').trim()).length),AlertTriangle],[language === 'es' ? 'Tareas abiertas' : 'Open tasks',String(openTasks.length),CircleGauge]].map(([label,value,Icon]) => { const IconComponent = Icon as React.ComponentType<{ className?: string }>; return <div key={String(label)} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#0A3F4D]/8"><IconComponent className="h-4.5 w-4.5 text-[#0A3F4D]" /></div><div><p className="text-sm font-semibold">{String(label)}</p><p className="text-xs text-black/45">{String(value)}</p></div></div></div>; })}</section>
  </>;
}
